name: xcam_one
description: 全景相机

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+9

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # 状态管理 https://github.com/rrousselGit/provider
  provider: ^5.0.0

  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^2.0.3
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^2.0.2
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^2.0.1

  # 本地存储 https://github.com/lesnitsky/flutter_localstorage
  localstorage: ^4.0.0+1

  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.0.0

  # WebView插件，不支持web端，可以考虑easy_web_view，或自行封装 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: ^2.0.2

  # 透明占位符，用于loading
  transparent_image: ^2.0.0

  # 图片拾取（从手机相册获取存取照片）https://github.com/flutter/plugins/tree/master/packages/image_picker/image_picker
  image_picker: ^0.7.4

  # 照片查看 https://github.com/fireslime/photo_view
  photo_view: ^0.11.1

  # 加载图标 https://github.com/jogboms/flutter_spinkit
  flutter_spinkit: ^5.0.0

  # 连接wifi https://github.com/flutter/plugins/tree/master/packages/connectivity/connectivity
  #  connectivity: ^3.0.3
  wifi_info_flutter: ^2.0.0
  connectivity_plus: ^1.0.0

  # Wi-Fi 查看wifi列表 https://github.com/alternadom/WiFiFlutter
  #  wifi_iot: ^0.3.0

  # 打开app设置 https://github.com/spencerccf/app_settings
  app_settings: ^4.1.0

  # 网络库 https://github.com/flutterchina/dio
  dio: ^4.0.0

  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^6.0.0

  # RTSP流播放 https://github.com/solid-software/flutter_vlc_player/
  flutter_vlc_player: 6.0.1

  # bilibi RTSP流播放 https://github.com/befovy/fijkplayer
  # fijkplayer: ^0.8.7

  # XML解析 https://github.com/renggli/dart-xml
  xml: ^5.0.2

  # xml to json  https://github.com/shamblett/xml2json
  xml2json: ^5.0.0

  #  # 权限检测 https://github.com/Baseflow/flutter-permission-handler
  #  permission_handler: ^6.1.1

  # 相册管理 https://github.com/CaiJingLong/flutter_photo_manager
  photo_manager: ^1.1.2

  cached_network_image: ^3.0.0

  # 包含图片编辑功能、缩放平移操作
  extended_image: ^4.0.1

  # 两个拉动刷新
  pull_to_refresh: ^1.6.5
  flutter_easyrefresh: ^2.2.1

  package_info: ^2.0.0

  # 倒计时
  #  timer_count_down: ^2.0.1
  circular_countdown_timer: ^0.2.0

  # 全景照片查看器
  panorama: ^0.4.1

  # socket client https://github.com/rikulo/socket.io-client-dart
  # socket_io_client: ^2.0.0-beta.3-nullsafety.0

  # 按钮按下动画放大缩小动画效果
  # bouncing_widget
  #dependency_overrides:
  #  http_parser: ^4.0.0
  #  plugin_platform_interface: ^2.0.0
  #  xml: ^5.0.2
  #  test_api: ^0.3.0 # 将测试dev dependencies 注释掉
  #  crypto: ^3.0.0
  #  convert: ^3.0.0
  #  args: ^2.0.0
  #  vm_service: ^6.1.0+1
  #  archive: ^3.1.2
  #  pub_semver: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #  fonts:
    #    - family: ZaoZiGongFangYingLiHeiGuiTi
    #      fonts:
    #        - asset: assets/fonts/ZaoZiGongFangYingLiHeiGuiTi.otf

    #    - family: SourceHanSansCN-Regular
    #      fonts:
    #        - asset: assets/fonts/SourceHanSansCN-Regular.otf
    #    - family: SourceHanSansCN-Bold
    #      fonts:
    #        - asset: assets/fonts/SourceHanSansCN-Bold.otf
    #    - family: SourceHanSansCN-ExtraLight
    #      fonts:
    #        - asset: assets/fonts/SourceHanSansCN-ExtraLight.otf
    #    - family: SourceHanSansCN-Heavy
    #      fonts:
    #        - asset: assets/fonts/SourceHanSansCN-Heavy.otf
    #    - family: SourceHanSansCN-Light
    #      fonts:
    #        - asset: assets/fonts/SourceHanSansCN-Light.otf
    #    - family: SourceHanSansCN-Medium
    #      fonts:
    #        - asset: assets/fonts/SourceHanSansCN-Medium.otf
    #    - family: SourceHanSansCN-Normal
    #      fonts:
    #        - asset: assets/fonts/SourceHanSansCN-Normal.otf

  #    - family: PingFangSC
  #      fonts:
  #        - asset: assets/fonts/PingFang_Regular.ttf
  #          weight: 400
  #        - asset: assets/fonts/PingFang_Medium.ttf
  #          weight: 500
  #        - asset: assets/fonts/PingFang_Light.ttf
  #          weight: 300
  #        - asset: assets/fonts/PingFang_Bold.ttf
  #          weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

#flutter_intl:
#  enabled: true
